server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/CarSystem
  rabbitmq:
    host: localhost
    port: 5672
    username: car
    password: car

queues:
  exchange: car-system
  exchangeDlq: car-system-dlq
  create: create
  update: update
  delete: delete
  dlqSuffix: -dlq
  routingKey: car-system.


