version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: car
      RABBITMQ_DEFAULT_PASS: car
    ports:
      - "5672:5672"
      - "15672:15672"